<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In - Marathi Medicos</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <h1>Sign In to Marathi Medicos</h1>
    <form id="sign-in-form">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <button type="submit">Sign In</button>
    </form>
    <p>Or sign in using:</p>
    <button id="google-signin">Sign in with Google</button>
    <button id="facebook-signin">Sign in with Facebook</button>

    <script src="https://www.gstatic.com/firebasejs/9.1.3/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.1.3/firebase-auth.js"></script>
    <script>
        // Your Firebase configuration
        const firebaseConfig = {
            apiKey: "YOUR_API_KEY",
            authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
            projectId: "YOUR_PROJECT_ID",
            storageBucket: "YOUR_PROJECT_ID.appspot.com",
            messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
            appId: "YOUR_APP_ID"
        };

        // Initialize Firebase
        const app = firebase.initializeApp(firebaseConfig);
        const auth = firebase.auth();

        // Google Sign-In
        document.getElementById('google-signin').addEventListener('click', function() {
            var provider = new firebase.auth.GoogleAuthProvider();
            auth.signInWithPopup(provider).then(function(result) {
                // Redirect to your main site or handle sign-in success
            }).catch(function(error) {
                console.error("Error during Google sign-in:", error);
            });
        });

        // Facebook Sign-In
        document.getElementById('facebook-signin').addEventListener('click', function() {
            var provider = new firebase.auth.FacebookAuthProvider();
            auth.signInWithPopup(provider).then(function(result) {
                // Redirect to your main site or handle sign-in success
            }).catch(function(error) {
                console.error("Error during Facebook sign-in:", error);
            });
        });

        // Email/Password Sign-In
        document.getElementById('sign-in-form').addEventListener('submit', function(event) {
            event.preventDefault();
            var email = document.getElementById('email').value;
            var password = document.getElementById('password').value;

            auth.signInWithEmailAndPassword(email, password).then(function(result) {
                // Redirect to your main site or handle sign-in success
            }).catch(function(error) {
                console.error("Error during email sign-in:", error);
            });
        });
    </script>
</body>
</html>
[AutoRun]
OPEN=SETUP.exe
ICON=ico.ico
